# Generated by Django 3.1.3 on 2020-11-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=256, verbose_name='Название события')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('question', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('full_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
